[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["darim92 <dario.caroprese@live.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.1"
chrono = "0.4.6"
